In [1]:
import numpy as np

#  1. Create a 3x3x3 Matrix with random value.

In [41]:
a = np.random.random((3,3,3))
a
# print(a)

array([[[0.72086505, 0.94586159, 0.28628424],
        [0.54737314, 0.84313406, 0.79688987],
        [0.82205209, 0.29423302, 0.29899264]],

       [[0.34488884, 0.73088474, 0.74411391],
        [0.09998264, 0.2309221 , 0.60356387],
        [0.86273797, 0.2721873 , 0.54266412]],

       [[0.8067251 , 0.82537684, 0.14086539],
        [0.13419071, 0.12769672, 0.10049207],
        [0.20982952, 0.99653693, 0.35622535]]])

 # 2.   Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [42]:
b = np.diag(1+np.arange(4),k =- 1)
b
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.  Create a 8x8 matrix and fill it with a checkerboard pattern.

In [44]:
x = np.zeros((8,8),dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix.

In [43]:
y = np.random.random((5,5))
y = (y - np.mean (y)) / (np.std (y))
print(y)

[[-0.09808516 -1.43506107 -0.36404687  1.08108764  0.01643177]
 [-1.57184809  1.19133773  1.11653808  0.34083864  1.36848034]
 [ 1.14201    -1.73548859 -0.62105907  1.05356301 -0.8795956 ]
 [ 0.11706941 -0.05019804  1.17646875 -1.75803427  0.4416083 ]
 [ 0.94811082  0.72086001 -0.6796128  -0.44872556 -1.07264938]]


# 5.  How to find common values between two arrays?

In [46]:
a = np.random.randint(0,10,10)
a1 = np.random.randint(0,10,10)
print(np.intersect1d(a,a1))

[0 5 7]


# 6.  How to get the dates of yesterday, today and tomorrow?

In [49]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print('Yesterday:',yesterday)
print('Today:' , today)
print('Tomorrow:' ,tomorrow)

Yesterday: 2020-08-01
Today: 2020-08-02
Tomorrow: 2020-08-03


# 7. Consider two random array A and B, check if they are equal.

In [50]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming the values
equal = np.allclose(A,B)
print(equal)

# Checkikg the values
equal = np.array_equal(A,B)
print(equal)

False
False


# 8. Create random vector of size 10 and replace the maximum value by 0. 

In [45]:
X = np.random.random(10)
X [X.argmax()] = 0
print(X)

[0.80139599 0.2034726  0.7133832  0.46135047 0.         0.03796744
 0.36913382 0.65183702 0.50943265 0.04350205]


# 9. How to print all the values of an array?

In [47]:
np.set_printoptions(threshold = float("inf"))
x = np.zeros((16,16))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10. Subtract the mean of each row of a matrix.

In [51]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[-0.32133959  0.14043767  0.05871972 -0.09366448  0.09190746 -0.2745465
  -0.13819979  0.34165963 -0.16984717  0.36487306]
 [ 0.34384413 -0.21916273  0.29891838  0.23107482 -0.1276111   0.1436228
   0.14338497 -0.34326862 -0.07230872 -0.39849393]
 [ 0.11992015 -0.20125398  0.13948205 -0.1580358   0.01680483 -0.06342716
  -0.09336869  0.13856874 -0.11996261  0.22127248]
 [ 0.13341009  0.08091873  0.03157875  0.14460091 -0.06916857  0.12919052
  -0.20044642 -0.02053854 -0.05213993 -0.17740554]
 [-0.22671744 -0.29416065  0.30526778 -0.14787612 -0.18902113 -0.34656867
   0.4287055   0.16706204 -0.08802194  0.39133063]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [53]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[3. 4. 2. 1. 4. 2. 5. 4. 2. 3.]


In [54]:
np.add.at(a, b, 1)
print(a)

[5. 7. 3. 1. 7. 3. 9. 7. 3. 5.]


# 12. How to get the diagonal of a dot product?

In [52]:
X = np.random.uniform(0,1,(5,5))
Y = np.random.uniform(0,1,(5,5))
# print(X)
# print(Y)

C =np.sum(X * Y.T, axis=1)
print("Diagonal of a dot product is....",C)

Diagonal of a dot product is.... [1.26302296 1.60704528 0.72117035 1.6295321  1.16751747]


# 13. How to find the most frequent value in an array?

In [57]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[9 3 8 2 5 4 5 4 1 5 4 5 5 4 8 1 0 2 0 1 6 1 6 2 0 6 5 6 3 3 1 5 4 3 7 4 9
 6 4 2 6 5 6 8 1 2 7 2 1 2]
5


# 14. How to get the n largest values of an array.

In [56]:
a = np.arange(30000)
np.random.shuffle(a)
n = 5

print (a[np.argsort(a)[-n:]])

[29995 29996 29997 29998 29999]


# 15. How to create a record array from a regular array?

In [55]:
a = np.array([("Hi", 1.5, 4),("People", 7.3, 9)])
b = np.core.records.fromarrays(a.T, names='col1, col2, col3',formats = 'S8, f8, i8')
#print(np.vstack(b)
print(b)

[(b'Hi', 1.5, 4) (b'People', 7.3, 9)]
